import "./globals.css"; // Import global CSS styles
import { ReduxProvider } from "../Redux/Provider"; // Import the Redux provider component
import { geistMono, geistSans } from "../styles/fonts.js"; // Import custom font styles

// Metadata for the layout, used by Next.js for SEO
export const metadata = {
  title: "Create Next App", // Page title
  description: "Generated by create next app", // Page description
};

// Root layout component for wrapping the application
export default function RootLayout({ children }) {
  return (
    <html lang="en"> {/* Specify the language of the document */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}> {/* Apply custom fonts */}
        <ReduxProvider>{children}</ReduxProvider> {/* Wrap children with Redux provider */}
      </body>
    </html>
  );
}
